export default {
  INFOR_USER: 'INFOR_USER',
  FETCH_DEPARTMENTS: 'FETCH_DEPARTMENTS',
  IS_LOADING: 'IS_LOADING',
  LOGOUT_ACCOUNT: 'LOGOUT_ACCOUNT',
  IS_LOGIN: 'IS_LOGIN',
  DISTANCE_LOCATION: 'DISTANCE_LOCATION',
  LOGIN_ACCOUNT: 'LOGIN_ACCOUNT',
  GET_ALL_BOOK: 'GET_ALL_BOOK',
  LOGIN: 'LOGIN',
  GET_ALL_AUTHOR: 'GET_ALL_AUTHOR',
  GET_ALL_CATEGORY: 'GET_ALL_CATEGORY',

  GET_NOTIFICATION_PRIVATE_READ: 'GET_NOTIFICATION_PRIVATE_READ',
  PUT_NOTIFICATION_PRIVATE_READER: 'PUT_NOTIFICATION_PRIVATE_READER',
  GET_LIST_NOTIFICATION: 'GET_LIST_NOTIFICATION',

  GET_ALL_CHAPTER_BY_ID: 'GET_ALL_CHAPTER_BY_ID',
  GET_ALL_BOOK_BY_CATEGORY: 'GET_ALL_BOOK_BY_CATEGORY',
  GET_ALL_BOOK_AUTHOR: 'GET_ALL_BOOK_AUTHOR',
  CHANGE_THEME: 'CHANGE_THEME',
};

export const _onSuccess = action => action + '_SUCCESS';
export const _onFail = action => action + '_FAIL';
export const _onUnmount = action => action + '_UNMOUNT';
